name = "Floof's Vanilla+ (Quilt)"
author = "Floof"
version = "2.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95c4711767b49006011750f5cb0da611ee3df80d92c1459b275e63cf805d5293"

[versions]
minecraft = "1.19.3"
quilt = "0.17.7"
