name = "Floof's Vanilla+ (Quilt)"
author = "Floof"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7916f968e23a09fd9109ed0b91c918df7626a804b607c9c2712355b9181da6fc"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"
