name = "Floof's Vanilla+ (Quilt)"
author = "Floof"
version = "2.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "beb0aa1110929e11a1f6073d3205d6154e39783ce297b288608ec8da305dd9ff"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"
