name = "Floof's Vanilla+ (Quilt)"
author = "Floof"
version = "2.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79fb1cfce9772d50eeb4e69b97e525081b759879f9789e18fe69a39d2bd63a18"

[versions]
minecraft = "1.19.3"
quilt = "0.17.8"
