name = "Floof's Vanilla+ (Quilt)"
author = "Floof"
version = "3.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c73c71e56660da0486898375fab0caa86543994c5b8646188a7fcfc0646c1ac2"

[versions]
fabric = "0.16.12"
minecraft = "25w14craftmine"

[options]
acceptable-game-versions = ["25w14craftmine"]
