name = "Floof's Vanilla+ (Quilt)"
author = "Floof"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66cfc224b2d12b087ff276dcfc589425ac5db40ef314373e1332a6aaa33fca12"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"
