name = "Floof's Vanilla+ (Quilt)"
author = "Floof"
version = "2.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2e2edfc1f654745305c10b5cea8fbace0375afa3f833e94d2025bd07ae2bcfe"

[versions]
minecraft = "1.19.3"
quilt = "0.17.7"
