name = "Floof's Vanilla+ (Quilt)"
author = "Floof"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3eefa3d414762940e9ff6c3c0d318ef2ad3df7b6dc4d19f559699e6a9f586476"

[versions]
minecraft = "1.19.2"
quilt = "0.17.6"
