name = "Floof's Vanilla+ (Quilt)"
author = "Floof"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "adbf3782f0d463aa474be13888b0d95def8065522f08089bd77c698f1886b715"

[versions]
fabric = "0.15.10"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.3", "1.20.4"]
