name = "Floof's Vanilla+ (Quilt)"
author = "Floof"
version = "2.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84b891c3037162061bce3101ffbfadd53f17fa6b0d9c6cd4be83ce32371f8c22"

[versions]
minecraft = "1.19.3"
quilt = "0.17.8"
